### ISSUE TITLE
No COM port with a NUC11PHBi7 running Win11

### ISSUE THREAD

**Issue by JulienMaille** [AlvinZhu/nuc_rgb#1]
Hi @AlvinZhu thanks for your python script.
I tried to use it under Windows, but my NUC doesn't expose any COM port. Is there anything to enable in the bios for it to show up? Or is something available ok the Extreme range but not on the Enthusiast models?
Thanks in advance

**Comment by AlvinZhu** [comment]
Only NUC 11/12 Extreme have been tested. I do not have a NUC11PHBi7.
you can use "intel nuc software studio" under Windows.
